spring:
  profiles:
    active: dev

---

spring:
  profiles:
    group:
      "dev": "dev"

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/review?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: heather
    password: review
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

server:
  http2:
    enabled: false
  port: 8081

grpc:
  port: 8082